name: Compilar notebooks de clases
on:
  push:
    branches:
      - master
jobs:
  build_notebooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Instalar dependencias
        run: |
          python3 -m pip install pipx
          python3 -m pipx ensurepath
          pipx install jupyterlab
          pipx install jupytext
          pip install -r requirements.txt
      - name: Compilar notebooks
        run: |
          for D in clases/*/; do jupytext --to notebook --execute ${D}*.py || true; done
      - name: Copiar notebooks
        if: always()
        run: |
          mkdir -p build/notebooks
          cp clases/**/*.ipynb --parents build/notebooks
          cp requirements.txt build/notebooks/clases
      - name: Install SSH Client 🔑
        if: always()
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Deployar notebooks 📓🚀
        if: always()
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BRANCH: notebooks
          FOLDER: build/notebooks/clases
          SSH: true
